name: metocean-ml
channels:
  - conda-forge
dependencies:
  - python=>3.9,<3.13
  - xarray
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - pytest
  - scikit-learn
  - pytorch
  - tqdm
  - roaring-landmask
  - shapely
  - pyproj
  - contextily
  - geopandas
  - skorch
  - netCDF4